name: test_app_checkbox
description: Test app checkbox

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: 3.0.6
  provider: ^4.0.5
  flutter_bloc: ^6.1.1
  flutter_map: any
  location: ^2.3.5
  background_location: ^0.0.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: 3.0.6
  json_annotation: ^3.0.1
  json_serializable: ^3.5.0
  swagger_dart_code_generator: any
  build_runner: ^1.10.1

flutter:
  uses-material-design: true